#!/usr/bin/env node
// ---------------------------------------------------------------------------
// CryptoBolt: JS bundling build step.
//
// The site's js/*.js modules already run in shared global scope, loaded via
// ordered <script> tags (no bundler, no ES modules — see js/00-config.js
// comments). This script just concatenates each page's module list, in the
// exact same order the HTML previously loaded them in, into a single file
// per page under js/dist/. That cuts each page from N HTTP requests down to
// 1-2, with byte-for-byte identical execution order and therefore identical
// behavior.
//
// The concatenated bundle is then minified with terser (dropping comments
// and whitespace, shortening local variable names). This step is what
// actually makes js/dist/*.js small — before this was added, bundle-home.js
// (the file app.html loads) shipped as a 271KB, comment-and-whitespace-heavy
// file, which was the single biggest contributor to slow load/interactivity
// on the terminal pages. Minification is skipped with a warning (not an
// error) if terser isn't installed, so `npm run build:js` still works on a
// fresh checkout before `npm install` — but the committed js/dist/*.js
// should always be built with terser available so what ships is minified.
//
// Source files in js/*.js remain the files to edit — js/dist/*.js is a build
// artifact, regenerated by `npm run build:js` (see also the "JS bundle is up
// to date" CI check in .github/workflows/, which mirrors the existing
// Tailwind staleness check).
// ---------------------------------------------------------------------------

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const JS_DIR = path.join(ROOT, 'js');
const DIST_DIR = path.join(JS_DIR, 'dist');

// Keep this in sync with the <script> order in each HTML page. If you add,
// remove, or reorder a module in a page's <script> tags, update the matching
// list below and re-run `npm run build:js`.
const BUNDLES = {
  // index.html
  'bundle-home.js': [
    '00-config.js',
    '01-state.js',
    '02-api.js',
    '03-ui-table.js',
    '04-ticker-sockets.js',
    '05-indicators.js',
    '06-chart-engine.js',
    '07-alerts.js',
    '08-portfolio.js',
    '09-sound-compare.js',
    '10-ai-insight.js',
    '11-performance-notes-funding.js',
    '12-events-init.js',
    '13-risk-calculator.js',
    '17-auth.js',
    '19-cloud-sync.js',
    '14-buy-sell-redirect.js',
    '15-risk-triggers.js',
    '20-scroll-reveal.js',
  ],
  // trade.html
  'bundle-trade.js': [
    '00-config.js',
    '16-paper-trading.js',
    '17-auth.js',
    '19-cloud-sync.js',
    '22-leaderboard.js',
    '20-scroll-reveal.js',
  ],
  // account.html
  'bundle-account.js': [
    '00-config.js',
    '17-auth.js',
    '19-cloud-sync.js',
    '18-account.js',
    '20-scroll-reveal.js',
  ],
  // invest.html (dedicated real-money buy/sell page — separate from paper trading)
  'bundle-invest.js': [
    '00-config.js',
    '17-auth.js',
    '21-invest.js',
    '14-buy-sell-redirect.js',
    '20-scroll-reveal.js',
  ],
};

mkdirSync(DIST_DIR, { recursive: true });

// Terser is an optional devDependency (see package.json). We resolve it
// dynamically rather than a static top-level import so that `npm run
// build:js` still works — producing an unminified bundle, with a warning —
// on a fresh checkout before `npm install` has run.
let minify = null;
try {
  ({ minify } = await import('terser'));
} catch {
  console.warn(
    '\n[build-js] terser is not installed — writing UNMINIFIED bundles.\n' +
    '[build-js] Run `npm install` (installs terser as a devDependency) and\n' +
    '[build-js] re-run `npm run build:js` before deploying, or the terminal\n' +
    '[build-js] pages will ship the full, unminified JS to every visitor.\n'
  );
}

for (const [outFile, modules] of Object.entries(BUNDLES)) {
  const parts = modules.map((mod) => {
    const filePath = path.join(JS_DIR, mod);
    const contents = readFileSync(filePath, 'utf8');
    return `// ==== ${mod} ====\n${contents}`;
  });

  const banner =
    `// AUTO-GENERATED by scripts/build-js.js — do not edit directly.\n` +
    `// Edit the source files in js/*.js instead, then run: npm run build:js\n\n`;

  const unminified = banner + parts.join('\n\n');
  const beforeBytes = Buffer.byteLength(unminified, 'utf8');

  let finalCode = unminified;
  let afterBytes = beforeBytes;

  if (minify) {
    // mangle: false — this bundle is plain global-scope <script> code, not a
    // module with a private scope, so several of these files intentionally
    // reference top-level `const`/`function` names declared in an earlier
    // module in the same bundle (e.g. 05-indicators.js using CW_STATE from
    // 01-state.js). Mangling local names is normally safe, but it's not
    // worth the risk of an accidental top-level rename breaking that
    // cross-file wiring — compress + whitespace/comment removal alone
    // already gets the bulk of the size win.
    const result = await minify(unminified, {
      compress: true,
      mangle: false,
      format: { comments: false },
    });
    if (result.code) {
      finalCode = result.code;
      afterBytes = Buffer.byteLength(finalCode, 'utf8');
    } else {
      console.warn(`[build-js] terser returned no output for ${outFile}, writing unminified.`);
    }
  }

  writeFileSync(path.join(DIST_DIR, outFile), finalCode);

  const savedPct = beforeBytes > 0 ? Math.round((1 - afterBytes / beforeBytes) * 100) : 0;
  console.log(
    `Built js/dist/${outFile} (${modules.length} modules, ` +
    `${(beforeBytes / 1024).toFixed(1)}KB -> ${(afterBytes / 1024).toFixed(1)}KB` +
    (minify ? `, -${savedPct}%)` : ', unminified)')
  );
}