#!/usr/bin/env node
// ---------------------------------------------------------------------------
// CryptoBolt: JS bundling build step.
//
// The site's js/*.js modules already run in shared global scope, loaded via
// ordered <script> tags (no bundler, no ES modules — see js/00-config.js
// comments). This script just concatenates each page's module list, in the
// exact same order the HTML previously loaded them in, into a single file
// per page under js/dist/. That cuts each page from N HTTP requests down to
// 1-2, with byte-for-byte identical execution order and therefore identical
// behavior.
//
// Source files in js/*.js remain the files to edit — js/dist/*.js is a build
// artifact, regenerated by `npm run build:js` (see also the "JS bundle is up
// to date" CI check in .github/workflows/, which mirrors the existing
// Tailwind staleness check).
// ---------------------------------------------------------------------------

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const JS_DIR = path.join(ROOT, 'js');
const DIST_DIR = path.join(JS_DIR, 'dist');

// Keep this in sync with the <script> order in each HTML page. If you add,
// remove, or reorder a module in a page's <script> tags, update the matching
// list below and re-run `npm run build:js`.
const BUNDLES = {
  // index.html
  'bundle-home.js': [
    '00-config.js',
    '01-state.js',
    '02-api.js',
    '03-ui-table.js',
    '04-ticker-sockets.js',
    '05-indicators.js',
    '06-chart-engine.js',
    '07-alerts.js',
    '08-portfolio.js',
    '09-sound-compare.js',
    '10-ai-insight.js',
    '11-performance-notes-funding.js',
    '12-events-init.js',
    '13-risk-calculator.js',
    '17-auth.js',
    '19-cloud-sync.js',
    '14-alchemypay.js',
    '15-risk-triggers.js',
    '20-scroll-reveal.js',
  ],
  // trade.html
  'bundle-trade.js': [
    '00-config.js',
    '16-paper-trading.js',
    '17-auth.js',
    '19-cloud-sync.js',
    '20-scroll-reveal.js',
  ],
  // account.html
  'bundle-account.js': [
    '00-config.js',
    '17-auth.js',
    '19-cloud-sync.js',
    '18-account.js',
    '20-scroll-reveal.js',
  ],
  // invest.html (dedicated real-money buy/sell page — separate from paper trading)
  'bundle-invest.js': [
    '00-config.js',
    '17-auth.js',
    '21-invest.js',
    '14-alchemypay.js',
    '20-scroll-reveal.js',
  ],
};

mkdirSync(DIST_DIR, { recursive: true });

for (const [outFile, modules] of Object.entries(BUNDLES)) {
  const parts = modules.map((mod) => {
    const filePath = path.join(JS_DIR, mod);
    const contents = readFileSync(filePath, 'utf8');
    return `// ==== ${mod} ====\n${contents}`;
  });

  const banner =
    `// AUTO-GENERATED by scripts/build-js.js — do not edit directly.\n` +
    `// Edit the source files in js/*.js instead, then run: npm run build:js\n\n`;

  writeFileSync(
    path.join(DIST_DIR, outFile),
    banner + parts.join('\n\n')
  );

  console.log(`Built js/dist/${outFile} (${modules.length} modules)`);
}