#!/usr/bin/env node
// ---------------------------------------------------------------------------
// CryptoBolt: CSS bundling build step (mirrors scripts/build-js.js).
//
// app.html (and its sibling pages) load their local stylesheets — the Tailwind build plus
// several hand-written CSS files — as separate <link rel="stylesheet"> tags. Every one of
// those is render-blocking: the browser can't paint anything until all of them have been
// fetched and parsed, so N separate files means N round trips on the critical path before
// first paint. This script concatenates each page's stylesheet list, in the exact same
// cascade order the HTML previously loaded them in, into a single file per page under
// css/dist/. That cuts the render-blocking request count from N down to 1 (plus the
// separate cross-origin Google Fonts stylesheet), with byte-for-byte identical cascade
// order and therefore identical styling.
//
// Source files in css/*.css remain the files to edit — css/dist/*.css is a build artifact,
// regenerated by `npm run build:css-bundle` (run after `npm run build:css`, which compiles
// Tailwind — this step bundles the *output* of that step together with the rest).
// ---------------------------------------------------------------------------

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const CSS_DIR = path.join(ROOT, 'css');
const DIST_DIR = path.join(CSS_DIR, 'dist');

// Keep this in sync with the <link rel="stylesheet"> order in each HTML page. If you add,
// remove, or reorder a local stylesheet on a page, update the matching list below and
// re-run `npm run build:css`. (The Google Fonts stylesheet stays a separate cross-origin
// <link> — it can't be bundled in.)
const BUNDLES = {
  // app.html, trade.html, invest.html, account.html, about.html, contact.html
  'bundle-home.css': [
    'tailwind.css',
    'styles.css',
    'shadcn-ui.css',
    'ui-elevate.css',
    'premium.css',
    'home.css',
    'redesign.css',
  ],
  // index.html, features.html (no shadcn-ui.css)
  'bundle-marketing.css': [
    'tailwind.css',
    'styles.css',
    'ui-elevate.css',
    'premium.css',
    'home.css',
    'redesign.css',
  ],
  // ai.html
  'bundle-ai.css': [
    'tailwind.css',
    'styles.css',
    'shadcn-ui.css',
    'ui-elevate.css',
    'premium.css',
    'home.css',
    'ai.css',
    'redesign.css',
  ],
};

mkdirSync(DIST_DIR, { recursive: true });

for (const [outFile, files] of Object.entries(BUNDLES)) {
  const parts = files.map((file) => {
    const filePath = path.join(CSS_DIR, file);
    const contents = readFileSync(filePath, 'utf8');
    return `/* ==== ${file} ==== */\n${contents}`;
  });

  const banner =
    `/* AUTO-GENERATED by scripts/build-css.js — do not edit directly.\n` +
    `   Edit the source files in css/*.css instead, then run: npm run build:css-bundle */\n\n`;

  const bundled = banner + parts.join('\n\n');
  const bytes = Buffer.byteLength(bundled, 'utf8');

  writeFileSync(path.join(DIST_DIR, outFile), bundled);
  console.log(`Built css/dist/${outFile} (${files.length} files, ${(bytes / 1024).toFixed(1)}KB)`);
}